; ==============================================================================
; 引脚配置总说明
; default：是否使用默认引脚配置（全局规则）
;   - 不设置 / 1：启用默认配置
;   - 0：禁用默认配置，使用自定义引脚
;   note:  默认引脚为底包 hwDrivecfg.def中定义的引脚, hwDrivecfg.def中为芯片脚，需要根据io复用表转换为模组脚使用。
;   pin:  模组引脚
;   func: 引脚复用功能
; ==============================================================================

[uart]
; ------------------------------------------------------------------------------
; UART 引脚配置说明
; 格式规则：
;   uart*_default = en          ; 是否启用该UART默认引脚（en=启用，dis=禁用）
;   uart*_pin_tx  = pin,func  ; TX引脚：功能编号
;   uart*_pin_rx  = pin,func  ; RX引脚：功能编号
;   uart*_pin_cts = pin,func  ; CTS引脚：功能编号
;   uart*_pin_rts = pin,func  ; RTS引脚：功能编号
; ------------------------------------------------------------------------------
uart0_default=1                ; 启用UART1默认引脚配置
uart1_default=1                ; 启用UART1默认引脚配置

; ------------------------------ 自定义引脚 -------------------------------------
; uart1_pin_tx=18,1
; uart1_pin_rx=17,1
; uart1_pin_cts=29,2
; uart1_pin_rts=28,2

[i2c]
; ------------------------------------------------------------------------------
; I2C 引脚配置说明
; 格式规则：
;   i2c*_default = en           ; 是否启用该I2C默认引脚（en=启用，dis=禁用）
;   i2c*_pin_scl = pin,func   ; SCL引脚：功能编号
;   i2c*_pin_sda = pin,func   ; SDA引脚：功能编号
; ------------------------------------------------------------------------------
i2c0_default=0                 ; 启用I2C0默认引脚配置
i2c1_default=0                 ; 启用I2C1默认引脚配置

; ------------------------------ 自定义引脚 -------------------------------------
i2c0_pin_scl=38,2
i2c0_pin_sda=39,2
i2c1_pin_scl=66,2
i2c1_pin_sda=57,3

[spi]
; ------------------------------------------------------------------------------
; SPI 引脚配置说明
; 格式规则：
;   spi*_default = en           ; 是否启用该SPI默认引脚（en=启用，dis=禁用）
;   spi*_pin_sclk = pin,func  ; SCLK引脚：功能编号（时钟）
;   spi*_pin_ssn  = pin,func  ; SSN引脚：功能编号（片选）
;   spi*_pin_mosi = pin,func  ; MOSI引脚：功能编号（输出）
;   spi*_pin_miso = pin,func  ; MISO引脚：功能编号（输入）
; ------------------------------------------------------------------------------
spi0_default=1                 ; 启用SPI0默认引脚配置
spi1_default=1                 ; 启用SPI1默认引脚配置

; ------------------------------ 自定义引脚 -------------------------------------
; spi0_pin_sclk=86,1
; spi0_pin_ssn=83,1 
; spi0_pin_mosi=85,1
; spi0_pin_miso=84,1

[cspi]
; ------------------------------------------------------------------------------
; CSPI 引脚配置说明
; 格式规则：
;   cspi*_default = en          ; 是否启用该CSPI默认引脚（en=启用，dis=禁用）
;   cspi*_pin_mclk = pin,func ; MCLK引脚：功能编号（主时钟）
;   cspi*_pin_pclk = pin,func ; PCLK引脚：功能编号（像素时钟）
;   cspi*_pin_cs   = pin,func ; CS引脚：功能编号（片选）
;   cspi*_pin_sdo0 = pin,func ; SDO0引脚：功能编号（数据输出0）
;   cspi*_pin_sdo1 = pin,func ; SDO1引脚：功能编号（数据输出1）
; ------------------------------------------------------------------------------
cspi0_default=1                ; 启用CSPI0默认引脚配置
cspi1_default=1                ; 启用CSPI1默认引脚配置

; ------------------------------ 自定义引脚 -------------------------------------
; cspi0_pin_mclk = {26, 1};
; cspi0_pin_pclk = {30, 1};
; cspi0_pin_cs = {31, 1};
; cspi0_pin_sdo0 = {32, 1};
; cspi0_pin_sdo1 = {33, 1};

[i2s]
; ------------------------------------------------------------------------------
; I2S 引脚配置说明
; 格式规则：
;   i2s*_default = en           ; 是否启用该I2S默认引脚（en=启用，dis=禁用）
;   i2s*_pin_mclk = pin,func  ; MCLK引脚：功能编号（主时钟）
;   i2s*_pin_bclk = pin,func  ; BCLK引脚：功能编号（位时钟）
;   i2s*_pin_lrck = pin,func  ; LRCK引脚：功能编号（左右声道时钟）
;   i2s*_pin_din  = pin,func  ; DIN引脚：功能编号（数据输入）
;   i2s*_pin_dout = pin,func  ; DOUT引脚：功能编号（数据输出）
; ------------------------------------------------------------------------------
i2s0_default=1                 ; 启用I2S0默认引脚配置
i2s1_default=1                 ; 启用I2S1默认引脚配置

; ------------------------------ 自定义引脚 -------------------------------------
; i2s0_pin_mclk = {26, 1};
; i2s0_pin_bclk = {30, 1};
; i2s0_pin_lrck = {31, 1};
; i2s0_pin_din = {32, 1};
; i2s0_pin_dout = {33, 1};
