#ifndef LIOT_API_EVENT_DEF_H
#define LIOT_API_EVENT_DEF_H

#ifdef __cplusplus
extern "C" {
#endif

#include "liot_api_common.h"

/***************************  task priority defination   ******************************/
typedef enum
{
    APP_PRIORITY_IDLE         = 1, // reserved
    APP_PRIORITY_LOW          = 4,
    APP_PRIORITY_BELOW_NORMAL = 8,
    APP_PRIORITY_NORMAL       = 12,
    APP_PRIORITY_ABOVE_NORMAL = 16,
    APP_PRIORITY_HIGH         = 25,
    APP_PRIORITY_REALTIME     = 30
} liot_app_ThreadPriority_e;

/****************************  error code about osi    ***************************/
typedef enum
{
    LIOT_OSI_SUCCESS = 0,

    LIOT_OSI_TASK_PARAM_INVALID = 1 | (LIOT_COMPONENT_OSI << 16),
    LIOT_OSI_TASK_CREATE_FAIL,
    LIOT_OSI_NO_MEMORY,
    LIOT_OSI_TASK_DELETE_FAIL,
    LIOT_OSI_TASK_PRIO_INVALID,
    LIOT_OSI_TASK_NAME_INVALID,
    LIOT_OSI_TASK_EVENT_COUNT_INVALID,
    LIOT_OSI_INVALID_TASK_REF,
    LIOT_OSI_TASK_CNT_REACH_MAX,
    LIOT_OSI_TASK_BIND_EVENT_FAIL,
    LIOT_OSI_TASK_UNBIND_EVENT_FAIL,
    LIOT_OSI_TASK_GET_REF_FAIL,
    LIOT_OSI_TASK_GET_PRIO_FAIL,
    LIOT_OSI_TASK_SET_PRIO_FAIL,
    LIOT_OSI_TASK_GET_STATUS_FAIL,
    LIOT_OSI_TASK_HAS_BINDED_TIMER,

    LIOT_OSI_QUEUE_CREATE_FAIL = 50 | (LIOT_COMPONENT_OSI << 16),
    LIOT_OSI_QUEUE_DELETE_FAIL,
    LIOT_OSI_QUEUE_IS_FULL,
    LIOT_OSI_QUEUE_RELEASE_FAIL,
    LIOT_OSI_QUEUE_RECEIVE_FAIL,
    LIOT_OSI_QUEUE_GET_CNT_FAIL,
    LIOT_OSI_QUEUE_IS_FAIL,
    LIOT_OSI_QUEUE_RESET_FAIL,

    LIOT_OSI_SEMA_CREATE_FAILE = 100 | (LIOT_COMPONENT_OSI << 16),
    LIOT_OSI_SEMA_DELETE_FAIL,
    LIOT_OSI_SEMA_IS_FULL,
    LIOT_OSI_SEMA_RELEASE_FAIL,
    LIOT_OSI_SEMA_GET_FAIL,
    LIOT_OSI_SEMA_FAIL,

    LIOT_OSI_MUTEX_CREATE_FAIL = 150 | (LIOT_COMPONENT_OSI << 16),
    LIOT_OSI_MUTEX_DELETE_FAIL,
    LIOT_OSI_MUTEX_LOCK_FAIL,
    LIOT_OSI_MUTEX_UNLOCK_FAIL,

    LIOT_OSI_EVENT_SEND_FAIL = 200 | (LIOT_COMPONENT_OSI << 16),
    LIOT_OSI_EVENT_GET_FAIL,
    LIOT_OSI_EVENT_REGISTER_FAIL,
    LIOT_OSI_EVENT_PARAM_INVALID,

    LIOT_OSI_TIMER_CREATE_FAIL = 250 | (LIOT_COMPONENT_OSI << 16),
    LIOT_OSI_TIMER_START_FAIL,
    LIOT_OSI_TIMER_STOP_FAIL,
    LIOT_OSI_TIMER_DELETE_FAIL,
    LIOT_OSI_TIMER_BIND_TASK_FAIL,

    LIOT_OSI_SWDOG_REGISTER_FAIL = 300 | (LIOT_COMPONENT_OSI << 16),
    LIOT_OSI_SWDOG_UNREGISTER_FAIL,
    LIOT_OSI_SWDOG_FEED_DOG_FAIL,
    LIOT_OSI_SWDOG_ENABLE_FAIL,
    LIOT_OSI_SWDOG_DISABLE_FAIL,

} liot_osi_errcode_e;

#ifdef __cplusplus
} /*"C" */
#endif

#endif
