#ifndef TIRTC_LFS_PREFIX_H
#define TIRTC_LFS_PREFIX_H
#define LFS_NO_MALLOC
#define LFS_NO_DEBUG
#define LFS_NO_WARN
#define LFS_NO_ERROR
#define LFS_MULTIVERSION
#define lfs_aligndown ts_lfs_aligndown
#define lfs_alignup ts_lfs_alignup
#define lfs_alloc ts_lfs_alloc
#define lfs_alloc_ckpoint ts_lfs_alloc_ckpoint
#define lfs_alloc_drop ts_lfs_alloc_drop
#define lfs_alloc_lookahead ts_lfs_alloc_lookahead
#define lfs_alloc_scan ts_lfs_alloc_scan
#define lfs_attr ts_lfs_attr
#define lfs_bd_cmp ts_lfs_bd_cmp
#define lfs_bd_crc ts_lfs_bd_crc
#define lfs_bd_erase ts_lfs_bd_erase
#define lfs_bd_flush ts_lfs_bd_flush
#define lfs_bd_prog ts_lfs_bd_prog
#define lfs_bd_read ts_lfs_bd_read
#define lfs_bd_sync ts_lfs_bd_sync
#define lfs_block_t ts_lfs_block_t
#define lfs_cache ts_lfs_cache
#define lfs_cache_drop ts_lfs_cache_drop
#define lfs_cache_t ts_lfs_cache_t
#define lfs_cache_zero ts_lfs_cache_zero
#define lfs_commit ts_lfs_commit
#define lfs_commitattr ts_lfs_commitattr
#define lfs_config ts_lfs_config
#define lfs_crc ts_lfs_crc
#define lfs_ctz ts_lfs_ctz
#define lfs_ctz_extend ts_lfs_ctz_extend
#define lfs_ctz_find ts_lfs_ctz_find
#define lfs_ctz_fromle32 ts_lfs_ctz_fromle32
#define lfs_ctz_index ts_lfs_ctz_index
#define lfs_ctz_tole32 ts_lfs_ctz_tole32
#define lfs_ctz_traverse ts_lfs_ctz_traverse
#define lfs_deinit ts_lfs_deinit
#define lfs_dir ts_lfs_dir
#define lfs_dir_alloc ts_lfs_dir_alloc
#define lfs_dir_close ts_lfs_dir_close
#define lfs_dir_close_ ts_lfs_dir_close_
#define lfs_dir_commit ts_lfs_dir_commit
#define lfs_dir_commit_commit ts_lfs_dir_commit_commit
#define lfs_dir_commit_size ts_lfs_dir_commit_size
#define lfs_dir_commitattr ts_lfs_dir_commitattr
#define lfs_dir_commitcrc ts_lfs_dir_commitcrc
#define lfs_dir_commitprog ts_lfs_dir_commitprog
#define lfs_dir_compact ts_lfs_dir_compact
#define lfs_dir_drop ts_lfs_dir_drop
#define lfs_dir_fetch ts_lfs_dir_fetch
#define lfs_dir_fetchmatch ts_lfs_dir_fetchmatch
#define lfs_dir_find ts_lfs_dir_find
#define lfs_dir_find_match ts_lfs_dir_find_match
#define lfs_dir_get ts_lfs_dir_get
#define lfs_dir_getgstate ts_lfs_dir_getgstate
#define lfs_dir_getinfo ts_lfs_dir_getinfo
#define lfs_dir_getread ts_lfs_dir_getread
#define lfs_dir_getslice ts_lfs_dir_getslice
#define lfs_dir_needsrelocation ts_lfs_dir_needsrelocation
#define lfs_dir_open ts_lfs_dir_open
#define lfs_dir_open_ ts_lfs_dir_open_
#define lfs_dir_orphaningcommit ts_lfs_dir_orphaningcommit
#define lfs_dir_read ts_lfs_dir_read
#define lfs_dir_read_ ts_lfs_dir_read_
#define lfs_dir_relocatingcommit ts_lfs_dir_relocatingcommit
#define lfs_dir_rewind ts_lfs_dir_rewind
#define lfs_dir_rewind_ ts_lfs_dir_rewind_
#define lfs_dir_seek ts_lfs_dir_seek
#define lfs_dir_seek_ ts_lfs_dir_seek_
#define lfs_dir_split ts_lfs_dir_split
#define lfs_dir_splittingcompact ts_lfs_dir_splittingcompact
#define lfs_dir_t ts_lfs_dir_t
#define lfs_dir_tell ts_lfs_dir_tell
#define lfs_dir_tell_ ts_lfs_dir_tell_
#define lfs_dir_traverse ts_lfs_dir_traverse
#define lfs_dir_traverse_filter ts_lfs_dir_traverse_filter
#define lfs_diskoff ts_lfs_diskoff
#define lfs_error ts_lfs_error
#define lfs_fcrc ts_lfs_fcrc
#define lfs_fcrc_fromle32 ts_lfs_fcrc_fromle32
#define lfs_fcrc_tole32 ts_lfs_fcrc_tole32
#define lfs_file ts_lfs_file
#define lfs_file_close ts_lfs_file_close
#define lfs_file_close_ ts_lfs_file_close_
#define lfs_file_config ts_lfs_file_config
#define lfs_file_flush ts_lfs_file_flush
#define lfs_file_flushedread ts_lfs_file_flushedread
#define lfs_file_flushedwrite ts_lfs_file_flushedwrite
#define lfs_file_open ts_lfs_file_open
#define lfs_file_open_ ts_lfs_file_open_
#define lfs_file_opencfg ts_lfs_file_opencfg
#define lfs_file_opencfg_ ts_lfs_file_opencfg_
#define lfs_file_outline ts_lfs_file_outline
#define lfs_file_read ts_lfs_file_read
#define lfs_file_read_ ts_lfs_file_read_
#define lfs_file_relocate ts_lfs_file_relocate
#define lfs_file_rewind ts_lfs_file_rewind
#define lfs_file_rewind_ ts_lfs_file_rewind_
#define lfs_file_seek ts_lfs_file_seek
#define lfs_file_seek_ ts_lfs_file_seek_
#define lfs_file_size ts_lfs_file_size
#define lfs_file_size_ ts_lfs_file_size_
#define lfs_file_sync ts_lfs_file_sync
#define lfs_file_sync_ ts_lfs_file_sync_
#define lfs_file_t ts_lfs_file_t
#define lfs_file_tell ts_lfs_file_tell
#define lfs_file_tell_ ts_lfs_file_tell_
#define lfs_file_truncate ts_lfs_file_truncate
#define lfs_file_truncate_ ts_lfs_file_truncate_
#define lfs_file_write ts_lfs_file_write
#define lfs_file_write_ ts_lfs_file_write_
#define lfs_format ts_lfs_format
#define lfs_format_ ts_lfs_format_
#define lfs_free ts_lfs_free
#define lfs_frombe32 ts_lfs_frombe32
#define lfs_fromle32 ts_lfs_fromle32
#define lfs_fs_demove ts_lfs_fs_demove
#define lfs_fs_deorphan ts_lfs_fs_deorphan
#define lfs_fs_desuperblock ts_lfs_fs_desuperblock
#define lfs_fs_disk_version ts_lfs_fs_disk_version
#define lfs_fs_disk_version_major ts_lfs_fs_disk_version_major
#define lfs_fs_disk_version_minor ts_lfs_fs_disk_version_minor
#define lfs_fs_forceconsistency ts_lfs_fs_forceconsistency
#define lfs_fs_gc ts_lfs_fs_gc
#define lfs_fs_gc_ ts_lfs_fs_gc_
#define lfs_fs_grow ts_lfs_fs_grow
#define lfs_fs_grow_ ts_lfs_fs_grow_
#define lfs_fs_mkconsistent ts_lfs_fs_mkconsistent
#define lfs_fs_mkconsistent_ ts_lfs_fs_mkconsistent_
#define lfs_fs_parent ts_lfs_fs_parent
#define lfs_fs_parent_match ts_lfs_fs_parent_match
#define lfs_fs_pred ts_lfs_fs_pred
#define lfs_fs_prepmove ts_lfs_fs_prepmove
#define lfs_fs_preporphans ts_lfs_fs_preporphans
#define lfs_fs_prepsuperblock ts_lfs_fs_prepsuperblock
#define lfs_fs_size ts_lfs_fs_size
#define lfs_fs_size_ ts_lfs_fs_size_
#define lfs_fs_size_count ts_lfs_fs_size_count
#define lfs_fs_stat ts_lfs_fs_stat
#define lfs_fs_stat_ ts_lfs_fs_stat_
#define lfs_fs_traverse ts_lfs_fs_traverse
#define lfs_fs_traverse_ ts_lfs_fs_traverse_
#define lfs_fsinfo ts_lfs_fsinfo
#define lfs_getattr ts_lfs_getattr
#define lfs_getattr_ ts_lfs_getattr_
#define lfs_gstate ts_lfs_gstate
#define lfs_gstate_fromle32 ts_lfs_gstate_fromle32
#define lfs_gstate_getorphans ts_lfs_gstate_getorphans
#define lfs_gstate_hasmove ts_lfs_gstate_hasmove
#define lfs_gstate_hasmovehere ts_lfs_gstate_hasmovehere
#define lfs_gstate_hasorphans ts_lfs_gstate_hasorphans
#define lfs_gstate_iszero ts_lfs_gstate_iszero
#define lfs_gstate_needssuperblock ts_lfs_gstate_needssuperblock
#define lfs_gstate_t ts_lfs_gstate_t
#define lfs_gstate_tole32 ts_lfs_gstate_tole32
#define lfs_gstate_xor ts_lfs_gstate_xor
#define lfs_info ts_lfs_info
#define lfs_init ts_lfs_init
#define lfs_lookahead ts_lfs_lookahead
#define lfs_malloc ts_lfs_malloc
#define lfs_mattr ts_lfs_mattr
#define lfs_max ts_lfs_max
#define lfs_mdir ts_lfs_mdir
#define lfs_mdir_t ts_lfs_mdir_t
#define lfs_migrate ts_lfs_migrate
#define lfs_migrate_ ts_lfs_migrate_
#define lfs_migration ts_lfs_migration
#define lfs_min ts_lfs_min
#define lfs_mkdir ts_lfs_mkdir
#define lfs_mkdir_ ts_lfs_mkdir_
#define lfs_mlist ts_lfs_mlist
#define lfs_mlist_append ts_lfs_mlist_append
#define lfs_mlist_isopen ts_lfs_mlist_isopen
#define lfs_mlist_remove ts_lfs_mlist_remove
#define lfs_mount ts_lfs_mount
#define lfs_mount_ ts_lfs_mount_
#define lfs_npw2 ts_lfs_npw2
#define lfs_off_t ts_lfs_off_t
#define lfs_open_flags ts_lfs_open_flags
#define lfs_pair_cmp ts_lfs_pair_cmp
#define lfs_pair_fromle32 ts_lfs_pair_fromle32
#define lfs_pair_isnull ts_lfs_pair_isnull
#define lfs_pair_issync ts_lfs_pair_issync
#define lfs_pair_swap ts_lfs_pair_swap
#define lfs_pair_tole32 ts_lfs_pair_tole32
#define lfs_popc ts_lfs_popc
#define lfs_remove ts_lfs_remove
#define lfs_remove_ ts_lfs_remove_
#define lfs_removeattr ts_lfs_removeattr
#define lfs_removeattr_ ts_lfs_removeattr_
#define lfs_rename ts_lfs_rename
#define lfs_rename_ ts_lfs_rename_
#define lfs_scmp ts_lfs_scmp
#define lfs_setattr ts_lfs_setattr
#define lfs_setattr_ ts_lfs_setattr_
#define lfs_size_t ts_lfs_size_t
#define lfs_soff_t ts_lfs_soff_t
#define lfs_ssize_t ts_lfs_ssize_t
#define lfs_stag_t ts_lfs_stag_t
#define lfs_stat ts_lfs_stat
#define lfs_stat_ ts_lfs_stat_
#define lfs_superblock ts_lfs_superblock
#define lfs_superblock_fromle32 ts_lfs_superblock_fromle32
#define lfs_superblock_t ts_lfs_superblock_t
#define lfs_superblock_tole32 ts_lfs_superblock_tole32
#define lfs_t ts_lfs_t
#define lfs_tag_chunk ts_lfs_tag_chunk
#define lfs_tag_dsize ts_lfs_tag_dsize
#define lfs_tag_id ts_lfs_tag_id
#define lfs_tag_isdelete ts_lfs_tag_isdelete
#define lfs_tag_isvalid ts_lfs_tag_isvalid
#define lfs_tag_size ts_lfs_tag_size
#define lfs_tag_splice ts_lfs_tag_splice
#define lfs_tag_t ts_lfs_tag_t
#define lfs_tag_type1 ts_lfs_tag_type1
#define lfs_tag_type2 ts_lfs_tag_type2
#define lfs_tag_type3 ts_lfs_tag_type3
#define lfs_tobe32 ts_lfs_tobe32
#define lfs_tole32 ts_lfs_tole32
#define lfs_type ts_lfs_type
#define lfs_unmount ts_lfs_unmount
#define lfs_unmount_ ts_lfs_unmount_
#define lfs_util ts_lfs_util
#define lfs_whence_flags ts_lfs_whence_flags
#endif
