# Tool suffix when cross-compiling
GCCLIB1_PATH ?=$(GCC_PATH)/lib/gcc/arm-none-eabi/10.2.1/thumb/v7-m/nofp
GCCLIB2_PATH ?= $(GCC_PATH)/arm-none-eabi/lib/thumb/v7-m/nofp

LD_FILE 		?= $(TOP)/components/kernel/app.ld

# Setup compilation params
CFLAGS_CPU      ?= -mcpu=cortex-m3 -mthumb

CFLAGS_OPTION   ?= -std=gnu99 -nostartfiles -mapcs-frame -specs=nano.specs
CFLAGS_OPTIMIZE ?= -Os -ffunction-sections -fdata-sections -fno-isolate-erroneous-paths-dereference -freorder-blocks-algorithm=stc
CFLAGS_ANALYSIS ?= #-fanalyzer
CFLAGS_WARNING  ?= -Wall -Wno-main

# compiler flags
CFLAGS += $(CFLAGS_CPU) $(CFLAGS_OPTION) $(CFLAGS_OPTIMIZE) $(CFLAGS_WARNING) $(CFLAGS_ANALYSIS) -D__CURRENT_FILE_NAME__=$(basename $(@F))

CFLAGS_ASM = -Wall -D__ASSEMBLY__ -mthumb -gdwarf-2 #-mthumb-interwork

DEPFLAGS = -MMD -MP -MT $(basename $@).o -MF $(basename $@).d 

# linker flags

LDFLAGS += -Wl,--print-memory-usage -Wl,--gc-sections

LDFLAGS += -L $(TOP)/apps/$(PROJECT)
